This error originates from a subprocess, and is likely not a problem with pip.